swagger: "2.0"
info: 
  version: "1.0.0"
  title: "KB test"
  description: "KB: testing OpenAPI"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "seralf"
    email: "seralf@gmail.com"
  license: 
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:9000
basePath: /kb/v1
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  "/time/now": 
    get: 
      summary: "returns the current time"
      description: "returns the current time"
      operationId: "getCurrentTime"
      produces: 
        - "application/json"
      responses: 
        200:
          description: "the current time"
          #examples: { "id": 3333, "time": "2017-06-28 11:12:00" }
          schema: 
            $ref: "#/definitions/Time"

definitions: 
  Time: 
    type: "object"
    required: 
      - "id"
      - "time"
    properties: 
      id: 
        type: "integer"
        format: "int64"
      time: 
        type: "string"
